//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dacsanviet.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBack
    {
        public long feedBack_ID { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string content { get; set; }
        public Nullable<bool> status { get; set; }
        public string createdDate { get; set; }
        public Nullable<long> product_ID { get; set; }
        public Nullable<long> about_ID { get; set; }
        public Nullable<long> news_ID { get; set; }
    
        public virtual About About { get; set; }
        public virtual News News { get; set; }
        public virtual Product Product { get; set; }
    }
}
