//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dacsanviet.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public News()
        {
            this.FeedBacks = new HashSet<FeedBack>();
        }
    
        public long news_ID { get; set; }
        public string title { get; set; }
        public string metatile { get; set; }
        public string descriptions { get; set; }
        public string newImage { get; set; }
        public Nullable<int> categories { get; set; }
        public string detail { get; set; }
        public string createdDate { get; set; }
        public string createdBy { get; set; }
        public string modifiedDate { get; set; }
        public string modifiedBy { get; set; }
        public string metaKeywords { get; set; }
        public string metaDescription { get; set; }
        public Nullable<bool> status { get; set; }
        public string topHot { get; set; }
        public Nullable<int> viewCount { get; set; }
        public Nullable<long> tag_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedBack> FeedBacks { get; set; }
        public virtual Tag Tag { get; set; }
        public virtual Tag Tag1 { get; set; }
    }
}
