//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dacsanviet.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public long orderDetail_ID { get; set; }
        public Nullable<long> order_ID { get; set; }
        public Nullable<long> product_ID { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
