//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dacsanviet.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.FeedBacks = new HashSet<FeedBack>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Stores = new HashSet<Store>();
        }
    
        public long product_ID { get; set; }
        public string productCode { get; set; }
        public string productName { get; set; }
        public string metatitle { get; set; }
        public string descriptions { get; set; }
        public string productImage { get; set; }
        public string moreImage { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> promotionPrice { get; set; }
        public Nullable<bool> includeVAT { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<long> productCategory_ID { get; set; }
        public string detail { get; set; }
        public Nullable<int> warranty { get; set; }
        public string createdDate { get; set; }
        public string createdBy { get; set; }
        public string modifiedDate { get; set; }
        public string modifiedBy { get; set; }
        public string metaKeywords { get; set; }
        public string metaDescription { get; set; }
        public Nullable<bool> status { get; set; }
        public string topHot { get; set; }
        public Nullable<int> viewCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedBack> FeedBacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Store> Stores { get; set; }
    }
}
