//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dacsanviet.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public long shop_ID { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public Nullable<long> product_ID { get; set; }
        public Nullable<long> company_ID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Product Product { get; set; }
    }
}
