//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dacsanviet.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long transaction_ID { get; set; }
        public Nullable<long> user_ID { get; set; }
        public Nullable<decimal> totalMoney { get; set; }
        public string payment { get; set; }
        public string payment_info { get; set; }
        public string message { get; set; }
        public string security { get; set; }
        public string createdDate { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
