//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dacsanviet.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long user_ID { get; set; }
        public string userName { get; set; }
        public string passWord { get; set; }
        public Nullable<bool> gender { get; set; }
        public string birthday { get; set; }
        public string phone { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string createdDate { get; set; }
        public string createdBy { get; set; }
        public string modifiedDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> typeLogin { get; set; }
    }
}
